# Generated by Django 3.1.7 on 2021-05-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('github', models.TextField()),
                ('first', models.CharField(max_length=15)),
                ('second', models.CharField(max_length=15)),
                ('third', models.CharField(max_length=15)),
            ],
        ),
    ]
