# Generated by Django 3.1.7 on 2021-05-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Backend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('optiona', models.TextField()),
                ('optionb', models.TextField()),
                ('optionc', models.TextField()),
                ('optiond', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
